services:
  - docker

matrix:
  fast_finish: true

script:
  - make build

after_success:
  - if [[ "${TRAVIS_TAG}" != "" ]]; then
    docker login -u udovicic -p "$DOCKER_PASSWORD";
    docker tag udovicic/elasticsearch:6.8 udovicic/elasticsearch:latest;
    docker tag udovicic/elasticsearch:6.8 udovicic/elasticsearch:${TRAVIS_TAG};
    docker push udovicic/elasticsearch:6.8;
    docker push udovicic/elasticsearch:latest;
    docker push udovicic/elasticsearch:${TRAVIS_TAG};
    fi